### ISSUE TITLE
generate_tiles.py - mapnik.load_map flag

### ISSUE THREAD

**Issue by Ircama** [StyXman/elevation#1]
Hi,

I think you might maintain the most updated/functional version of *generate_tiles.py*.

I would suggest to consider revising the hardcoded setting of the *strict* flag in `mapnik.load_map`.

Possibly, it might be set to *False* like

    mapnik.load_map(self.m, mapfile, False)

or alternatively parametrized through a command-line option.

It will avoid errors like:

    RuntimeError: Failed to find font face 'unifont Medium' in FontSet 'book-fonts'

**Comment by StyXman** [comment]
So that was it! I'll try to do it this weekend. Thanks for the heads up!

**Comment by StyXman** [comment]
Bam, done :)

**Comment by Ircama** [comment]
Thanks, perfect.

I have just tested your modification and it works.
